name: Tests for Request Polling example

on:
  workflow_dispatch:


jobs:
  test:
    # https://github.com/bahmutov/cypress-workflows
    uses: bahmutov/cypress-workflows/.github/workflows/split.yml@v1
    with:
      browser: chrome